<?php
/**
 * @category    Foggyline
 * @package     Foggyline_SearchOrder
 * @author      Branko Ajzele <ajzele@gmail.com>
 * @copyright   Copyright (c) Branko Ajzele (http://foggyline.net/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $helper = Mage::helper('foggyline_searchorder') ?>
<?php if ($helper->isModuleEnabled() && ($flCodes = $helper->getAttrCodes())): ?>
<script type="text/javascript">
//<![CDATA[
document.observe("dom:loaded", function() {
    var flCodes = <?php echo json_encode(array_reverse($flCodes)) ?>;
    var searchListEl = $('advanced-search-list');

    if (searchListEl) {
        for (i=0; i<flCodes.length; i++) {
            if ((el = flCodes[i]) && $(el)) {
                searchListEl.insert({ top: $(el).up(1).remove() });
            }
        }
    }
});
//]]>
</script>
<?php endif; ?>